#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : My Book  # The title of the book. Will be placed in the left navbar.
author                      : Sulthan A. Karimov  # The author of the book
copyright                   : "2024"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  exclude_patterns: 
    - default

  ## Define the name of the latex output file for PDF builds
  #latex:
  #  latex_documents:
  #    targetname: book.tex
  #
  ## Add a bibtex file so that we can create citations
  #bibtex_bibfiles:
  #  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/sakarimov/My Book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  extra_extensions:
    - ablog
    - sphinx.ext.intersphinx
  config:
    #html_theme: shibuya
    #    html_theme: alabaster
    #html_theme: pydata-sphinx-theme
    html_title: Just Another Attempt to Share
    #html_sidebars:
    #  '**':
    #    #- sidebars/localtoc.html
    #    - ablog/postcard.html
    #    - ablog/tagcloud.html
    #    - ablog/recentposts.html
    #    - ablog/categories.html
        #html_theme_options:
        #  nav_links:
        #    - title: Home
        #      url: https://github.com/sakarimov
